version: '3.3'

services:
  cluster-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: cluster-elasticsearch
    ports:
      - "9202:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    ports: 
      - "5601:5601"
    environment: 
      - ELASTICSEARCH_HOSTS=http://cluster-elasticsearch:9200